import os
import app_explorer

visited_pkg = ['bubei.tingshu', 'cn.TuHu.android', 'cn.com.sina.finance', 'cn.eclicks.wzsearch', 'cn.kuwo.player', 'com.baidu.duer.superapp', 'com.gkid.crazyrope', 'com.gotokeep.keep', 'com.hnjc.dl', 'com.hpbr.bosszhipin', 'com.hunantv.imgo.activity', 'com.imaginer.yunji', 'com.immomo.momo', 'com.kingsoft', 'com.lingan.seeyou', 'com.mt.mtxx.mtxx', 'com.netease.cbg', 'com.netease.cloudmusic', 'com.pingan.papd', 'com.qiyi.video', 'com.qzone', 'com.sina.weibo', 'com.smzdm.client.android', 'com.tencent.karaoke', 'com.tencent.qqpim', 'com.tieyou.train.ark', 'com.tongcheng.android', 'com.tsingzone.questionbank', 'com.videogo', 'com.wuba.bangjob', 'com.xingin.xhs', 'com.xunmeng.pingduoduo', 'com.yipiao', 'com.yitantech.gaigai', 'com.yunmai.scale', 'com.zenmen.palmchat', 'com.zhihu.android', 'ctrip.android.view', 'net.csdn.csdnplus']

all_pkg = ['bubei.tingshu', 'cn.com.langeasy.LangEasyLexis', 'cn.com.sina.finance', 'cn.eclicks.wzsearch', 'cn.kuwo.player', 'cn.TuHu.android', 'cn.wps.moffice', 'com.babycloud.hanju', 'com.baidu.duer.superapp', 'com.baidu.netdisk', 'com.baidu.newapp', 'com.baidu.searchbox', 'com.cat.readall', 'com.cctv.yangshipin.app.androidp', 'com.cmcc.cmvideo', 'com.cmri.universalapp', 'com.dragon.read', 'com.duolingo', 'com.fenbi.android.servant', 'com.gkid.crazyrope', 'com.gotokeep.keep', 'com.hexin.plat.android', 'com.hnjc.dl', 'com.hortor.juliancysj', 'com.hpbr.bosszhipin', 'com.hunantv.imgo.activity', 'com.imaginer.yunji', 'com.immomo.momo', 'com.jingdong.app.mall', 'com.jiongji.andriod.card', 'com.kingsoft', 'com.kmxs.reader', 'com.kuaiduizuoye.scan', 'com.kuaishou.nebula', 'com.kugou.android.lite', 'com.kugou.android', 'com.kwai.hisense', 'com.kwai.videoeditor', 'com.larus.nova', 'com.lingan.seeyou', 'com.lofter.android', 'com.luna.music', 'com.MobileTicket', 'com.mogujie', 'com.moonshot.kimichat', 'com.mt.mtxx.mtxx', 'com.netease.cbg', 'com.netease.cloudmusic', 'com.netease.uu', 'com.phoenix.read', 'com.pingan.papd', 'com.qclianai.com', 'com.qidian.QDReader', 'com.qiyi.video', 'com.qq.reader', 'com.quark.browser', 'com.qzone', 'com.seetong.app.seetong', 'com.shizhuang.duapp', 'com.sina.weibo', 'com.smile.gifmaker', 'com.smzdm.client.android', 'com.ss.android.article.lite', 'com.ss.android.article.news', 'com.ss.android.article.video', 'com.ss.android.ugc.live', 'com.taobao.idlefish', 'com.taobao.taobao', 'com.tencent.androidqqmail', 'com.tencent.docs', 'com.tencent.karaoke', 'com.tencent.mm', 'com.tencent.mobileqq', 'com.tencent.qqlive', 'com.tencent.qqmusic', 'com.tencent.qqpim', 'com.tencent.wemeet.app', 'com.tencent.weread', 'com.tencent.wework', 'com.tieyou.train.ark', 'com.tongcheng.android', 'com.tsingzone.questionbank', 'com.videogo', 'com.wuba.bangjob', 'com.xiaoe.client', 'com.xiaomi.smarthome', 'com.ximalaya.ting.android', 'com.xingin.xhs', 'com.xingye.app', 'com.xs.fm.lite', 'com.xs.fm', 'com.xunmeng.merchant', 'com.xunmeng.pinduoduo', 'com.yipiao', 'com.yitantech.gaigai', 'com.youku.phone', 'com.yueme.itv', 'com.yunmai.scale', 'com.zenmen.palmchat', 'com.zhaopin.social', 'com.zhihu.android', 'com.zhihu.vip.android', 'ctrip.android.view', 'net.csdn.csdnplus', 'tv.danmaku.bili']

all_pkg_en = ['org.telegram.messenger', 'com.newleaf.app.android.victor', 'com.facebook.orca', 'com.snapchat.android', 'com.paypal.android.p2pmobile', 'com.mcdonalds.app', 'com.netflix.mediaclient', 'com.enflick.android.TextNow', 'com.espn.fantasy.lm.football', 'com.imdb.mobile', 'com.life360.android.safetymapd', 'com.education.android.h.intelligence', 'com.instabridge.android', 'com.spotify.music', 'com.instagram.barcelona', 'com.grammarly.android.keyboard', 'com.google.android.apps.translate', 'com.ubercab.eats', 'com.canva.editor', 'com.yahoo.mobile.client.android.sportacular', 'us.zoom.videomeetings', 'com.facebook.lite', 'com.gotv.nflgamecenter.us.lite', 'com.iqiyi.i18n', 'com.moodle.moodlemobile', 'com.offbeattech.everuts', 'com.bilibili.app.in', 'com.whatsapp.w4b', 'com.global.foodpanda.android', 'com.nwfb', 'com.memeandsticker.textsticker', 'com.tumblr', 'com.mearsure.heartratepro.manage', 'com.instagram.lite', 'com.parknshop.parknshopapp', 'hk.schoolink.platform', 'sg.decathlon.app', 'com.forhy.clobaltimes', 'com.xingin.xhs', 'ai.chat.gpt.bot', 'com.fastretailing.stylehint', 'com.tvb.mytvsuper', 'jp.pxv.android', 'com.shkp.shkmalls', 'com.qrcodescanner.barcodereader.qrcode', 'com.loeqm.jpurger', 'com.instructure.candroid', 'com.sankuai.sailor.courier', 'com.codespaceapps.aichat', 'com.storymatrix.drama', 'gogolook.callgogolook2', 'com.sigstick.myapp', 'com.baitu.qingshu', 'hk.gogovan.GoGoVanClient2', 'sg.partying.android.lite', 'fr.vestiairecollective', 'com.p1.mobile.putong', 'jp.gocro.smartnews.android', 'com.ultimate.cleanerpro.ucp']
visited_pkg_en = ['org.telegram.messenger', 'com.newleaf.app.android.victor', 'com.facebook.orca', 'com.snapchat.android', 'com.paypal.android.p2pmobile', 'com.mcdonalds.app', 'com.netflix.mediaclient', 'com.enflick.android.TextNow', 'com.espn.fantasy.lm.football', 'com.imdb.mobile', 'com.life360.android.safetymapd', 'com.education.android.h.intelligence', 'com.instabridge.android']


if __name__ == '__main__':
    try:
        for pkg in all_pkg:
            if pkg in visited_pkg:
                continue
            app_explorer.main(pkg)
            visited_pkg.append(pkg)
    except Exception as e:
        print(e)
    finally:
        print(visited_pkg)
